name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    run-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run API Tests
        run: newman run RestfulBookerBVT.postman_collection.json -e Production.postman_environment.json
